import { USState, Industry, InjuryType } from '@/types'

export const EXCLUDED_STATES = ['ohio', 'washington', 'wyoming']

export const US_STATES: USState[] = [
  // ── Top 10 ────────────────────────────────────────────────────────────────
  { slug: 'california',   name: 'California',    abbr: 'CA', maxWeeklyBenefit: 1619, ttdRate: 0.6667, system: 'pdrs',
    avgSettlement: { low: 15000, high: 95000 }, sol: '1 year from injury', attorneyFeeRate: 0.15,
    statute: 'California Labor Code §3600–3602', statLink: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=3600.',
    regulator: 'CA Division of Workers Compensation (DWC)', regulatorLink: 'https://www.dir.ca.gov/dwc/',
    reportingDays: 30, filingDeadlineDays: 365 },

  { slug: 'texas',        name: 'Texas',          abbr: 'TX', maxWeeklyBenefit: 1066, ttdRate: 0.70,   system: 'ama',
    avgSettlement: { low: 8000,  high: 75000 }, sol: '1 year from injury', attorneyFeeRate: 0.15,
    statute: 'Texas Labor Code Chapter 408', statLink: 'https://statutes.capitol.texas.gov/Docs/LA/htm/LA.408.htm',
    regulator: 'TX Dept of Insurance, Division of Workers Comp', regulatorLink: 'https://www.tdi.texas.gov/wc/',
    reportingDays: 30, filingDeadlineDays: 365 },

  { slug: 'florida',      name: 'Florida',        abbr: 'FL', maxWeeklyBenefit: 1323, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 80000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Florida Statutes Chapter 440', statLink: 'https://www.flsenate.gov/Laws/Statutes/2023/Chapter440',
    regulator: 'FL Division of Workers Compensation', regulatorLink: 'https://www.myfloridacfo.com/division/wc/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'new-york',     name: 'New York',       abbr: 'NY', maxWeeklyBenefit: 1145, ttdRate: 0.6667, system: 'scheduled',
    avgSettlement: { low: 12000, high: 90000 }, sol: '2 years from injury', attorneyFeeRate: 0.15,
    statute: "New York Workers' Compensation Law §10", statLink: 'https://www.wcb.ny.gov/content/main/wclaws/wclaws.jsp',
    regulator: "NY Workers' Compensation Board", regulatorLink: 'https://www.wcb.ny.gov/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'illinois',     name: 'Illinois',       abbr: 'IL', maxWeeklyBenefit: 1897, ttdRate: 0.6667, system: 'percentage-of-person',
    avgSettlement: { low: 14000, high: 100000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'Illinois Workers Compensation Act 820 ILCS 305', statLink: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=2301',
    regulator: 'IL Workers Compensation Commission', regulatorLink: 'https://www2.illinois.gov/sites/iwcc/',
    reportingDays: 45, filingDeadlineDays: 1095 },

  { slug: 'pennsylvania', name: 'Pennsylvania',   abbr: 'PA', maxWeeklyBenefit: 1325, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 11000, high: 85000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'Pennsylvania Workers Compensation Act 77 P.S. §1', statLink: 'https://www.legis.state.pa.us/cfdocs/legis/LI/uconsCheck.cfm?txtType=HTM&yr=1915&sessInd=0&smthLwInd=0&act=338',
    regulator: 'PA Bureau of Workers Compensation', regulatorLink: 'https://www.dli.pa.gov/Individuals/Workers-Compensation/',
    reportingDays: 21, filingDeadlineDays: 1095 },

  { slug: 'georgia',      name: 'Georgia',        abbr: 'GA', maxWeeklyBenefit: 800,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.25,
    statute: 'Georgia Workers Compensation Act O.C.G.A. §34-9-1', statLink: 'https://law.justia.com/codes/georgia/title-34/chapter-9/',
    regulator: 'GA State Board of Workers Compensation', regulatorLink: 'https://sbwc.georgia.gov/',
    reportingDays: 30, filingDeadlineDays: 365 },

  { slug: 'new-jersey',   name: 'New Jersey',     abbr: 'NJ', maxWeeklyBenefit: 1131, ttdRate: 0.70,   system: 'scheduled',
    avgSettlement: { low: 10000, high: 80000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'New Jersey Workers Compensation Law N.J.S.A. 34:15-1', statLink: 'https://law.justia.com/codes/new-jersey/title-34/section-34-15-1/',
    regulator: 'NJ Division of Workers Compensation', regulatorLink: 'https://www.nj.gov/labor/wc/',
    reportingDays: 14, filingDeadlineDays: 730 },

  { slug: 'michigan',     name: 'Michigan',       abbr: 'MI', maxWeeklyBenefit: 1120, ttdRate: 0.80,   system: 'wage-loss',
    avgSettlement: { low: 12000, high: 88000 }, sol: '2 years from injury', attorneyFeeRate: 0.15,
    statute: 'Michigan Workers Disability Compensation Act MCL 418.101', statLink: 'https://www.legislature.mi.gov/Laws/MCL?objectName=MCL-Act-317-of-1969',
    regulator: 'MI Workers Disability Compensation Agency', regulatorLink: 'https://www.michigan.gov/leo/bureaus-agencies/wdca',
    reportingDays: 90, filingDeadlineDays: 730 },

  { slug: 'colorado',     name: 'Colorado',       abbr: 'CO', maxWeeklyBenefit: 1325, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 72000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Colorado Workers Compensation Act C.R.S. §8-40-101', statLink: 'https://leg.colorado.gov/agencies/office-legislative-legal-services/colorado-revised-statutes',
    regulator: 'CO Division of Workers Compensation', regulatorLink: 'https://cdle.colorado.gov/dwc',
    reportingDays: 10, filingDeadlineDays: 730 },

  // ── Remaining 37 states ───────────────────────────────────────────────────
  { slug: 'arizona',        name: 'Arizona',        abbr: 'AZ', maxWeeklyBenefit: 1208, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '1 year from injury', attorneyFeeRate: 0.25,
    statute: 'Arizona Workers Compensation A.R.S. §23-901', statLink: 'https://www.azleg.gov/arstitle/',
    regulator: 'AZ Industrial Commission', regulatorLink: 'https://www.ica.state.az.us/',
    reportingDays: 10, filingDeadlineDays: 365 },

  { slug: 'north-carolina', name: 'North Carolina', abbr: 'NC', maxWeeklyBenefit: 1254, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'NC Workers Compensation Act N.C.G.S. §97-1', statLink: 'https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_97.html',
    regulator: 'NC Industrial Commission', regulatorLink: 'https://www.ic.nc.gov/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'virginia',       name: 'Virginia',       abbr: 'VA', maxWeeklyBenefit: 1318, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 70000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Virginia Workers Compensation Act Va. Code §65.2-100', statLink: 'https://law.lis.virginia.gov/vacode/title65.2/',
    regulator: 'VA Workers Compensation Commission', regulatorLink: 'https://www.vwc.state.va.us/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'tennessee',      name: 'Tennessee',      abbr: 'TN', maxWeeklyBenefit: 1116, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.20,
    statute: 'Tennessee Workers Compensation T.C.A. §50-6-101', statLink: 'https://law.justia.com/codes/tennessee/title-50/chapter-6/',
    regulator: 'TN Bureau of Workers Compensation', regulatorLink: 'https://www.tn.gov/workforce/injuries-at-work/workers-comp-main.html',
    reportingDays: 15, filingDeadlineDays: 365 },

  { slug: 'minnesota',      name: 'Minnesota',      abbr: 'MN', maxWeeklyBenefit: 1500, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 11000, high: 82000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'Minnesota Workers Compensation Act Minn. Stat. §176', statLink: 'https://www.revisor.mn.gov/statutes/cite/176',
    regulator: 'MN Department of Labor and Industry', regulatorLink: 'https://www.dli.mn.gov/workers-comp',
    reportingDays: 14, filingDeadlineDays: 1095 },

  { slug: 'missouri',       name: 'Missouri',       abbr: 'MO', maxWeeklyBenefit: 1083, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Missouri Workers Compensation §287 RSMo', statLink: 'https://revisor.mo.gov/main/OneChapter.aspx?chapter=287',
    regulator: 'MO Division of Workers Compensation', regulatorLink: 'https://labor.mo.gov/DWC',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'wisconsin',      name: 'Wisconsin',      abbr: 'WI', maxWeeklyBenefit: 1458, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 10000, high: 78000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Wisconsin Workers Compensation Act Wis. Stat. §102', statLink: 'https://docs.legis.wisconsin.gov/statutes/statutes/102',
    regulator: 'WI Department of Workforce Development', regulatorLink: 'https://dwd.wisconsin.gov/wc/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'indiana',        name: 'Indiana',        abbr: 'IN', maxWeeklyBenefit: 1124, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 62000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Indiana Workers Compensation Act I.C. §22-3-2', statLink: 'https://iga.in.gov/legislative/laws/2023/ic/titles/022/',
    regulator: "IN Worker's Compensation Board", regulatorLink: 'https://www.in.gov/wcb/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'maryland',       name: 'Maryland',       abbr: 'MD', maxWeeklyBenefit: 1266, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 72000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: "Maryland Workers' Compensation Act Lab. & Empl. §9-101", statLink: 'https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gle&section=9-101',
    regulator: "MD Workers' Compensation Commission", regulatorLink: 'https://www.wcc.state.md.us/',
    reportingDays: 10, filingDeadlineDays: 730 },

  { slug: 'alaska',         name: 'Alaska',         abbr: 'AK', maxWeeklyBenefit: 1464, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 12000, high: 85000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Alaska Workers Compensation Act AS §23.30', statLink: 'https://www.akleg.gov/basis/statutes.asp#23.30',
    regulator: 'AK Workers Compensation Division', regulatorLink: 'https://labor.alaska.gov/wc/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'louisiana',      name: 'Louisiana',      abbr: 'LA', maxWeeklyBenefit: 750,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 55000 }, sol: '1 year from injury', attorneyFeeRate: 0.20,
    statute: 'Louisiana Workers Compensation Act La. R.S. §23:1021', statLink: 'https://www.legis.la.gov/legis/Law.aspx?d=76326',
    regulator: 'LA Office of Workers Compensation Administration', regulatorLink: 'https://www.laworks.net/WorkersComp/OWC_MainMenu.asp',
    reportingDays: 30, filingDeadlineDays: 365 },

  { slug: 'kentucky',       name: 'Kentucky',       abbr: 'KY', maxWeeklyBenefit: 1196, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 68000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Kentucky Workers Compensation Act KRS §342', statLink: 'https://apps.legislature.ky.gov/law/statutes/chapter.aspx?id=39237',
    regulator: 'KY Department of Workers Claims', regulatorLink: 'https://labor.ky.gov/workers-claims/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'oklahoma',       name: 'Oklahoma',       abbr: 'OK', maxWeeklyBenefit: 954,  ttdRate: 0.70,   system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Oklahoma Workers Compensation Code 85A O.S. §1', statLink: 'https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=467585',
    regulator: 'OK Workers Compensation Commission', regulatorLink: 'https://www.owcc.state.ok.us/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'connecticut',    name: 'Connecticut',    abbr: 'CT', maxWeeklyBenefit: 1412, ttdRate: 0.75,   system: 'ama',
    avgSettlement: { low: 10000, high: 80000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'Connecticut Workers Compensation Act C.G.S. §31-275', statLink: 'https://www.cga.ct.gov/current/pub/chap_568.htm',
    regulator: 'CT Workers Compensation Commission', regulatorLink: 'https://wcc.state.ct.us/',
    reportingDays: 30, filingDeadlineDays: 1095 },

  { slug: 'utah',           name: 'Utah',           abbr: 'UT', maxWeeklyBenefit: 1162, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '3 years from injury', attorneyFeeRate: 0.25,
    statute: 'Utah Workers Compensation Act U.C.A. §34A-2-101', statLink: 'https://le.utah.gov/xcode/Title34A/Chapter2/34A-2.html',
    regulator: 'UT Labor Commission', regulatorLink: 'https://laborcommission.utah.gov/',
    reportingDays: 180, filingDeadlineDays: 1095 },

  { slug: 'nevada',         name: 'Nevada',         abbr: 'NV', maxWeeklyBenefit: 1156, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 68000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Nevada Industrial Insurance Act NRS §616A', statLink: 'https://www.leg.state.nv.us/nrs/nrs-616a.html',
    regulator: 'NV Division of Industrial Relations', regulatorLink: 'https://dir.nv.gov/',
    reportingDays: 7, filingDeadlineDays: 730 },

  { slug: 'arkansas',       name: 'Arkansas',       abbr: 'AR', maxWeeklyBenefit: 878,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Arkansas Workers Compensation Law A.C.A. §11-9-101', statLink: 'https://advance.lexis.com/container?config=0345494EJAA5ZjE0MDIyYy0yYzk4LTRlYmQtYWE4MS02ZTM4ZTFiNzMwZGQ%3D',
    regulator: 'AR Workers Compensation Commission', regulatorLink: 'https://awcc.state.ar.us/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'mississippi',    name: 'Mississippi',    abbr: 'MS', maxWeeklyBenefit: 616,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 5000,  high: 45000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Mississippi Workers Compensation Law Miss. Code §71-3-1', statLink: 'https://law.justia.com/codes/mississippi/title-71/chapter-3/',
    regulator: 'MS Workers Compensation Commission', regulatorLink: 'https://www.mwcc.ms.gov/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'kansas',         name: 'Kansas',         abbr: 'KS', maxWeeklyBenefit: 837,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 52000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Kansas Workers Compensation Act K.S.A. §44-501', statLink: 'https://kslegislature.org/li/b2023_24/statute/044_000_0000_chapter/044_005_0000_article/',
    regulator: 'KS Division of Workers Compensation', regulatorLink: 'https://www.dol.ks.gov/WC',
    reportingDays: 10, filingDeadlineDays: 730 },

  { slug: 'new-mexico',     name: 'New Mexico',     abbr: 'NM', maxWeeklyBenefit: 1046, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.25,
    statute: 'New Mexico Workers Compensation Act N.M.S.A. §52-1-1', statLink: 'https://law.justia.com/codes/new-mexico/chapter-52/article-1/',
    regulator: 'NM Workers Compensation Administration', regulatorLink: 'https://workerscomp.nm.gov/',
    reportingDays: 15, filingDeadlineDays: 365 },

  { slug: 'nebraska',       name: 'Nebraska',       abbr: 'NE', maxWeeklyBenefit: 1006, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Nebraska Workers Compensation Act Neb. Rev. Stat. §48-101', statLink: 'https://nebraskalegislature.gov/laws/statutes.php?statute=48-101',
    regulator: 'NE Workers Compensation Court', regulatorLink: 'https://www.wcc.ne.gov/',
    reportingDays: 10, filingDeadlineDays: 730 },

  { slug: 'idaho',          name: 'Idaho',          abbr: 'ID', maxWeeklyBenefit: 935,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Idaho Workers Compensation Law I.C. §72-101', statLink: 'https://legislature.idaho.gov/statutesrules/idstat/title72/',
    regulator: 'ID Industrial Commission', regulatorLink: 'https://iic.idaho.gov/',
    reportingDays: 60, filingDeadlineDays: 730 },

  { slug: 'hawaii',         name: 'Hawaii',         abbr: 'HI', maxWeeklyBenefit: 1157, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: "Hawaii Workers' Compensation Law HRS §386-1", statLink: 'https://www.capitol.hawaii.gov/hrscurrent/Vol07_Ch0346-0398/HRS0386/',
    regulator: 'HI Disability Compensation Division', regulatorLink: 'https://labor.hawaii.gov/dcd/',
    reportingDays: 7, filingDeadlineDays: 730 },

  { slug: 'maine',          name: 'Maine',          abbr: 'ME', maxWeeklyBenefit: 1060, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'Maine Workers Compensation Act 39-A M.R.S.A. §101', statLink: 'https://legislature.maine.gov/statutes/39-A/title39-Ach1sec0.html',
    regulator: 'ME Workers Compensation Board', regulatorLink: 'https://www.maine.gov/wcb/',
    reportingDays: 10, filingDeadlineDays: 730 },

  { slug: 'new-hampshire',  name: 'New Hampshire',  abbr: 'NH', maxWeeklyBenefit: 1534, ttdRate: 0.60,   system: 'ama',
    avgSettlement: { low: 9000,  high: 70000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'NH Workers Compensation Law RSA §281-A', statLink: 'https://www.gencourt.state.nh.us/rsa/html/XXIII/281-A/281-A-mrg.htm',
    regulator: 'NH Department of Labor', regulatorLink: 'https://www.labor.nh.gov/workers-compensation',
    reportingDays: 14, filingDeadlineDays: 1095 },

  { slug: 'rhode-island',   name: 'Rhode Island',   abbr: 'RI', maxWeeklyBenefit: 1457, ttdRate: 0.75,   system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: "Rhode Island Workers' Compensation Act R.I.G.L. §28-29-1", statLink: 'https://law.justia.com/codes/rhode-island/title-28/chapter-28-29/',
    regulator: 'RI Workers Compensation Court', regulatorLink: 'https://www.courts.ri.gov/Courts/WorkersCompensationCourt/',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'montana',        name: 'Montana',        abbr: 'MT', maxWeeklyBenefit: 870,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Montana Workers Compensation Act MCA §39-71-101', statLink: 'https://leg.mt.gov/bills/mca/title_0390/chapter_0710/',
    regulator: 'MT Department of Labor and Industry', regulatorLink: 'https://dli.mt.gov/workers-comp-claims',
    reportingDays: 30, filingDeadlineDays: 730 },

  { slug: 'delaware',       name: 'Delaware',       abbr: 'DE', maxWeeklyBenefit: 980,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Delaware Workers Compensation 19 Del. C. §2301', statLink: 'https://delcode.delaware.gov/title19/c023/',
    regulator: 'DE Office of Workers Compensation', regulatorLink: 'https://dia.workforcecenter.com/owc/',
    reportingDays: 10, filingDeadlineDays: 730 },

  { slug: 'south-dakota',   name: 'South Dakota',   abbr: 'SD', maxWeeklyBenefit: 954,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 48000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'South Dakota Workers Compensation SDCL §62-1', statLink: 'https://sdlegislature.gov/Statutes/Codified_Laws/2047591',
    regulator: 'SD Department of Labor and Regulation', regulatorLink: 'https://dlr.sd.gov/workers_compensation/',
    reportingDays: 3, filingDeadlineDays: 730 },

  { slug: 'north-dakota',   name: 'North Dakota',   abbr: 'ND', maxWeeklyBenefit: 1124, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'North Dakota Workforce Safety & Insurance N.D.C.C. §65-01', statLink: 'https://www.legis.nd.gov/cencode/t65c01.html',
    regulator: 'ND Workforce Safety & Insurance', regulatorLink: 'https://www.workforcesafety.com/',
    reportingDays: 7, filingDeadlineDays: 730 },

  { slug: 'vermont',        name: 'Vermont',        abbr: 'VT', maxWeeklyBenefit: 1367, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '3 years from injury', attorneyFeeRate: 0.20,
    statute: 'Vermont Workers Compensation 21 V.S.A. §601', statLink: 'https://legislature.vermont.gov/statutes/chapter/21/009',
    regulator: 'VT Department of Labor', regulatorLink: 'https://labor.vermont.gov/workers-compensation',
    reportingDays: 72, filingDeadlineDays: 1095 },

  { slug: 'alabama',        name: 'Alabama',        abbr: 'AL', maxWeeklyBenefit: 1054, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '2 years from injury', attorneyFeeRate: 0.15,
    statute: 'Alabama Workers Compensation Act Ala. Code §25-5-1', statLink: 'https://law.justia.com/codes/alabama/title-25/chapter-5/',
    regulator: 'AL Department of Labor Workers Compensation Division', regulatorLink: 'https://www.labor.alabama.gov/wc/',
    reportingDays: 5, filingDeadlineDays: 730 },

  { slug: 'south-carolina', name: 'South Carolina', abbr: 'SC', maxWeeklyBenefit: 1037, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: "South Carolina Workers' Compensation Law S.C. Code §42-1-10", statLink: 'https://www.scstatehouse.gov/code/title42.php',
    regulator: "SC Workers' Compensation Commission", regulatorLink: 'https://wcc.sc.gov/',
    reportingDays: 90, filingDeadlineDays: 730 },

  { slug: 'oregon',         name: 'Oregon',         abbr: 'OR', maxWeeklyBenefit: 1492, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Oregon Workers Compensation ORS §656.001', statLink: 'https://oregon.public.law/statutes/ors_656.001',
    regulator: 'OR Workers Compensation Division', regulatorLink: 'https://wcd.oregon.gov/',
    reportingDays: 90, filingDeadlineDays: 730 },

  { slug: 'massachusetts',  name: 'Massachusetts',  abbr: 'MA', maxWeeklyBenefit: 1694, ttdRate: 0.60,   system: 'ama',
    avgSettlement: { low: 12000, high: 85000 }, sol: '4 years from injury', attorneyFeeRate: 0.15,
    statute: "Massachusetts Workers' Compensation Act M.G.L. c.152", statLink: 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXXI/Chapter152',
    regulator: 'MA Department of Industrial Accidents', regulatorLink: 'https://www.mass.gov/orgs/department-of-industrial-accidents',
    reportingDays: 7, filingDeadlineDays: 1460 },

  { slug: 'iowa',           name: 'Iowa',           abbr: 'IA', maxWeeklyBenefit: 1994, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.25,
    statute: 'Iowa Workers Compensation Act Iowa Code §85', statLink: 'https://www.legis.iowa.gov/law/iowaCode/sections?codeChapter=85',
    regulator: 'IA Division of Workers Compensation', regulatorLink: 'https://www.iwd.iowa.gov/workers-compensation',
    reportingDays: 90, filingDeadlineDays: 730 },

  { slug: 'west-virginia',  name: 'West Virginia',  abbr: 'WV', maxWeeklyBenefit: 1018, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 55000 }, sol: '2 years from injury', attorneyFeeRate: 0.20,
    statute: 'West Virginia Workers Compensation W. Va. Code §23-1-1', statLink: 'https://code.wvlegislature.gov/23-1/',
    regulator: 'WV Offices of the Insurance Commissioner', regulatorLink: 'https://www.wvinsurance.gov/Workers-Compensation',
    reportingDays: 60, filingDeadlineDays: 730 },
]

export const INDUSTRIES: Industry[] = [
  { slug: 'construction',  name: 'Construction',         riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['back-injury', 'fall-injury', 'hand-injury', 'head-injury'] },
  { slug: 'manufacturing', name: 'Manufacturing',         riskLevel: 'high',      riskMultiplier: 1.25,
    commonInjuries: ['equipment-injury', 'repetitive-strain', 'amputation'] },
  { slug: 'warehouse',     name: 'Warehouse & Logistics', riskLevel: 'high',      riskMultiplier: 1.2,
    commonInjuries: ['back-injury', 'lifting-injury', 'repetitive-strain'] },
  { slug: 'transport',     name: 'Transportation',        riskLevel: 'high',      riskMultiplier: 1.2,
    commonInjuries: ['vehicle-accident', 'back-injury', 'neck-injury'] },
  { slug: 'healthcare',    name: 'Healthcare',            riskLevel: 'medium',    riskMultiplier: 1.1,
    commonInjuries: ['back-injury', 'needlestick', 'repetitive-strain'] },
  { slug: 'agriculture',   name: 'Agriculture',           riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['equipment-injury', 'fall-injury', 'heat-illness'] },
  { slug: 'retail',        name: 'Retail',                riskLevel: 'low',       riskMultiplier: 1.0,
    commonInjuries: ['slip-fall', 'lifting-injury', 'repetitive-strain'] },
  { slug: 'food-service',  name: 'Food Service',          riskLevel: 'medium',    riskMultiplier: 1.1,
    commonInjuries: ['burn-injury', 'slip-fall', 'repetitive-strain'] },
  { slug: 'mining',        name: 'Mining',                riskLevel: 'very-high', riskMultiplier: 1.5,
    commonInjuries: ['lung-disease', 'equipment-injury', 'head-injury'] },
  { slug: 'utilities',     name: 'Utilities',             riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['electrical-injury', 'fall-injury', 'burn-injury'] },
  { slug: 'office',        name: 'Office & Admin',        riskLevel: 'low',       riskMultiplier: 0.9,
    commonInjuries: ['carpal-tunnel', 'repetitive-strain', 'slip-fall'] },
  { slug: 'education',     name: 'Education',             riskLevel: 'low',       riskMultiplier: 0.9,
    commonInjuries: ['slip-fall', 'back-injury', 'ptsd'] },
]

export const INJURY_TYPES: InjuryType[] = [
  // Body part injuries
  { slug: 'back-injury',       name: 'Back & Spine Injury',         category: 'body-part',   bodyPart: 'back',
    scheduledWeeks: null, avgImpairmentRating: 15, avgMedicalCost: 45000, nyWeeks: null,  njWeeks: null },
  { slug: 'knee-injury',       name: 'Knee Injury',                  category: 'body-part',   bodyPart: 'leg',
    scheduledWeeks: 200,  avgImpairmentRating: 12, avgMedicalCost: 25000, nyWeeks: 288,   njWeeks: 315 },
  { slug: 'shoulder-injury',   name: 'Shoulder Injury',              category: 'body-part',   bodyPart: 'arm',
    scheduledWeeks: 160,  avgImpairmentRating: 14, avgMedicalCost: 30000, nyWeeks: 312,   njWeeks: 330 },
  { slug: 'hand-injury',       name: 'Hand & Wrist Injury',          category: 'body-part',   bodyPart: 'hand',
    scheduledWeeks: 244,  avgImpairmentRating: 10, avgMedicalCost: 20000, nyWeeks: 244,   njWeeks: 245 },
  { slug: 'foot-injury',       name: 'Foot & Ankle Injury',          category: 'body-part',   bodyPart: 'foot',
    scheduledWeeks: 205,  avgImpairmentRating: 10, avgMedicalCost: 18000, nyWeeks: 205,   njWeeks: 230 },
  { slug: 'neck-injury',       name: 'Neck & Cervical Injury',       category: 'body-part',   bodyPart: 'neck',
    scheduledWeeks: null, avgImpairmentRating: 12, avgMedicalCost: 38000, nyWeeks: null,  njWeeks: null },
  { slug: 'head-injury',       name: 'Head & Brain Injury (TBI)',    category: 'body-part',   bodyPart: 'head',
    scheduledWeeks: null, avgImpairmentRating: 25, avgMedicalCost: 85000, nyWeeks: null,  njWeeks: null },
  { slug: 'eye-injury',        name: 'Eye Injury / Vision Loss',     category: 'body-part',   bodyPart: 'eye',
    scheduledWeeks: 160,  avgImpairmentRating: 20, avgMedicalCost: 22000, nyWeeks: 160,   njWeeks: 200 },
  { slug: 'amputation',        name: 'Amputation',                   category: 'body-part',   bodyPart: 'varies',
    scheduledWeeks: 312,  avgImpairmentRating: 45, avgMedicalCost: 120000, nyWeeks: 312,  njWeeks: 330 },
  // Accident types
  { slug: 'fall-injury',       name: 'Fall / Slip & Trip',           category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 18, avgMedicalCost: 35000, nyWeeks: null,  njWeeks: null },
  { slug: 'equipment-injury',  name: 'Machinery & Equipment Injury', category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 50000, nyWeeks: null,  njWeeks: null },
  { slug: 'repetitive-strain', name: 'Repetitive Strain Injury (RSI)', category: 'accident',  bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 15000, nyWeeks: null,  njWeeks: null },
  { slug: 'lifting-injury',    name: 'Lifting & Overexertion',       category: 'accident',    bodyPart: 'back',
    scheduledWeeks: null, avgImpairmentRating: 13, avgMedicalCost: 28000, nyWeeks: null,  njWeeks: null },
  { slug: 'vehicle-accident',  name: 'Work Vehicle Accident',        category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 15, avgMedicalCost: 42000, nyWeeks: null,  njWeeks: null },
  { slug: 'burn-injury',       name: 'Burn Injury',                  category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 55000, nyWeeks: null,  njWeeks: null },
  { slug: 'electrical-injury', name: 'Electrical Injury',            category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 22, avgMedicalCost: 48000, nyWeeks: null,  njWeeks: null },
  { slug: 'heat-illness',      name: 'Heat Stroke / Heat Illness',   category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 20000, nyWeeks: null,  njWeeks: null },
  { slug: 'slip-fall',         name: 'Slip & Fall on Wet Surface',   category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 12, avgMedicalCost: 22000, nyWeeks: null,  njWeeks: null },
  // Occupational diseases
  { slug: 'carpal-tunnel',     name: 'Carpal Tunnel Syndrome',       category: 'occupational', bodyPart: 'hand',
    scheduledWeeks: 244,  avgImpairmentRating: 8,  avgMedicalCost: 12000, nyWeeks: 244,   njWeeks: 245 },
  { slug: 'hearing-loss',      name: 'Occupational Hearing Loss',    category: 'occupational', bodyPart: 'ear',
    scheduledWeeks: 150,  avgImpairmentRating: 15, avgMedicalCost: 8000,  nyWeeks: 150,   njWeeks: null },
  { slug: 'mesothelioma',      name: 'Mesothelioma / Asbestos Disease', category: 'occupational', bodyPart: 'lung',
    scheduledWeeks: null, avgImpairmentRating: 80, avgMedicalCost: 250000, nyWeeks: null, njWeeks: null },
  { slug: 'lung-disease',      name: 'Occupational Lung Disease',    category: 'occupational', bodyPart: 'lung',
    scheduledWeeks: null, avgImpairmentRating: 30, avgMedicalCost: 75000, nyWeeks: null,  njWeeks: null },
  { slug: 'ptsd',              name: 'Work-Related PTSD',            category: 'occupational', bodyPart: 'mental',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 30000, nyWeeks: null,  njWeeks: null },
  { slug: 'needlestick',       name: 'Needlestick / Blood Exposure', category: 'occupational', bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 5,  avgMedicalCost: 8000,  nyWeeks: null,  njWeeks: null },
  { slug: 'skin-disease',      name: 'Occupational Skin Disease',    category: 'occupational', bodyPart: 'skin',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 12000, nyWeeks: null,  njWeeks: null },
  { slug: 'chemical-exposure', name: 'Toxic Chemical Exposure',      category: 'occupational', bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 25, avgMedicalCost: 60000, nyWeeks: null,  njWeeks: null },
]
