import { USState, Industry, InjuryType } from '@/types'

export const EXCLUDED_STATES = ['ohio', 'washington', 'wyoming']

export const US_STATES: USState[] = [
  // ── Top 10 (spec-specified) ────────────────────────────────────────────
  { slug: 'california',   name: 'California',    abbr: 'CA', maxWeeklyBenefit: 1619, ttdRate: 0.6667, system: 'pdrs',
    avgSettlement: { low: 15000, high: 95000 }, sol: '1 year from injury', attorneyFeeRate: 0.15 },
  { slug: 'texas',        name: 'Texas',          abbr: 'TX', maxWeeklyBenefit: 1066, ttdRate: 0.70,   system: 'ama',
    avgSettlement: { low: 8000,  high: 75000 }, sol: '1 year from injury', attorneyFeeRate: 0.15 },
  { slug: 'florida',      name: 'Florida',        abbr: 'FL', maxWeeklyBenefit: 1323, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 80000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'new-york',     name: 'New York',       abbr: 'NY', maxWeeklyBenefit: 1145, ttdRate: 0.6667, system: 'scheduled',
    avgSettlement: { low: 12000, high: 90000 }, sol: '2 years from injury', attorneyFeeRate: 0.15 },
  { slug: 'illinois',     name: 'Illinois',       abbr: 'IL', maxWeeklyBenefit: 1897, ttdRate: 0.6667, system: 'percentage-of-person',
    avgSettlement: { low: 14000, high: 100000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'pennsylvania', name: 'Pennsylvania',   abbr: 'PA', maxWeeklyBenefit: 1325, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 11000, high: 85000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'georgia',      name: 'Georgia',        abbr: 'GA', maxWeeklyBenefit: 800,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.25 },
  { slug: 'new-jersey',   name: 'New Jersey',     abbr: 'NJ', maxWeeklyBenefit: 1131, ttdRate: 0.70,   system: 'scheduled',
    avgSettlement: { low: 10000, high: 80000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'michigan',     name: 'Michigan',       abbr: 'MI', maxWeeklyBenefit: 1120, ttdRate: 0.80,   system: 'wage-loss',
    avgSettlement: { low: 12000, high: 88000 }, sol: '2 years from injury', attorneyFeeRate: 0.15 },
  { slug: 'colorado',     name: 'Colorado',       abbr: 'CO', maxWeeklyBenefit: 1325, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 72000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },

  // ── Remaining 37 states ───────────────────────────────────────────────
  { slug: 'arizona',        name: 'Arizona',        abbr: 'AZ', maxWeeklyBenefit: 1208, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '1 year from injury', attorneyFeeRate: 0.25 },
  { slug: 'north-carolina', name: 'North Carolina', abbr: 'NC', maxWeeklyBenefit: 1254, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'virginia',       name: 'Virginia',       abbr: 'VA', maxWeeklyBenefit: 1318, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 70000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'tennessee',      name: 'Tennessee',      abbr: 'TN', maxWeeklyBenefit: 1116, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.20 },
  { slug: 'minnesota',      name: 'Minnesota',      abbr: 'MN', maxWeeklyBenefit: 1500, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 11000, high: 82000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'missouri',       name: 'Missouri',       abbr: 'MO', maxWeeklyBenefit: 1083, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'wisconsin',      name: 'Wisconsin',      abbr: 'WI', maxWeeklyBenefit: 1458, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 10000, high: 78000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'indiana',        name: 'Indiana',        abbr: 'IN', maxWeeklyBenefit: 1124, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 62000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'maryland',       name: 'Maryland',       abbr: 'MD', maxWeeklyBenefit: 1266, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 9000,  high: 72000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'alaska',         name: 'Alaska',         abbr: 'AK', maxWeeklyBenefit: 1464, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 12000, high: 85000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'louisiana',      name: 'Louisiana',      abbr: 'LA', maxWeeklyBenefit: 750,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 55000 }, sol: '1 year from injury', attorneyFeeRate: 0.20 },
  { slug: 'kentucky',       name: 'Kentucky',       abbr: 'KY', maxWeeklyBenefit: 1196, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 68000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'oklahoma',       name: 'Oklahoma',       abbr: 'OK', maxWeeklyBenefit: 954,  ttdRate: 0.70,   system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'connecticut',    name: 'Connecticut',    abbr: 'CT', maxWeeklyBenefit: 1412, ttdRate: 0.75,   system: 'ama',
    avgSettlement: { low: 10000, high: 80000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'utah',           name: 'Utah',           abbr: 'UT', maxWeeklyBenefit: 1162, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '3 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'nevada',         name: 'Nevada',         abbr: 'NV', maxWeeklyBenefit: 1156, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 68000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'arkansas',       name: 'Arkansas',       abbr: 'AR', maxWeeklyBenefit: 878,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'mississippi',    name: 'Mississippi',    abbr: 'MS', maxWeeklyBenefit: 616,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 5000,  high: 45000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'kansas',         name: 'Kansas',         abbr: 'KS', maxWeeklyBenefit: 837,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 52000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'new-mexico',     name: 'New Mexico',     abbr: 'NM', maxWeeklyBenefit: 1046, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '1 year from injury', attorneyFeeRate: 0.25 },
  { slug: 'nebraska',       name: 'Nebraska',       abbr: 'NE', maxWeeklyBenefit: 1006, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'idaho',          name: 'Idaho',          abbr: 'ID', maxWeeklyBenefit: 935,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'hawaii',         name: 'Hawaii',         abbr: 'HI', maxWeeklyBenefit: 1157, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'maine',          name: 'Maine',          abbr: 'ME', maxWeeklyBenefit: 1060, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'new-hampshire',  name: 'New Hampshire',  abbr: 'NH', maxWeeklyBenefit: 1534, ttdRate: 0.60,   system: 'ama',
    avgSettlement: { low: 9000,  high: 70000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'rhode-island',   name: 'Rhode Island',   abbr: 'RI', maxWeeklyBenefit: 1457, ttdRate: 0.75,   system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'montana',        name: 'Montana',        abbr: 'MT', maxWeeklyBenefit: 870,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 50000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'delaware',       name: 'Delaware',       abbr: 'DE', maxWeeklyBenefit: 980,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'south-dakota',   name: 'South Dakota',   abbr: 'SD', maxWeeklyBenefit: 954,  ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 6000,  high: 48000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'north-dakota',   name: 'North Dakota',   abbr: 'ND', maxWeeklyBenefit: 1124, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'vermont',        name: 'Vermont',        abbr: 'VT', maxWeeklyBenefit: 1367, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 8000,  high: 65000 }, sol: '3 years from injury', attorneyFeeRate: 0.20 },
  { slug: 'alabama',        name: 'Alabama',        abbr: 'AL', maxWeeklyBenefit: 1054, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 60000 }, sol: '2 years from injury', attorneyFeeRate: 0.15 },
  { slug: 'south-carolina', name: 'South Carolina', abbr: 'SC', maxWeeklyBenefit: 1037, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 58000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'oregon',         name: 'Oregon',         abbr: 'OR', maxWeeklyBenefit: 1492, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'massachusetts',  name: 'Massachusetts',  abbr: 'MA', maxWeeklyBenefit: 1694, ttdRate: 0.60,   system: 'ama',
    avgSettlement: { low: 12000, high: 85000 }, sol: '4 years from injury', attorneyFeeRate: 0.15 },
  { slug: 'iowa',           name: 'Iowa',           abbr: 'IA', maxWeeklyBenefit: 1994, ttdRate: 0.80,   system: 'ama',
    avgSettlement: { low: 10000, high: 75000 }, sol: '2 years from injury', attorneyFeeRate: 0.25 },
  { slug: 'west-virginia',  name: 'West Virginia',  abbr: 'WV', maxWeeklyBenefit: 1018, ttdRate: 0.6667, system: 'ama',
    avgSettlement: { low: 7000,  high: 55000 }, sol: '2 years from injury', attorneyFeeRate: 0.20 },
]

export const INDUSTRIES: Industry[] = [
  { slug: 'construction',  name: 'Construction',         riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['back-injury', 'fall-injury', 'hand-injury', 'head-injury'] },
  { slug: 'manufacturing', name: 'Manufacturing',         riskLevel: 'high',      riskMultiplier: 1.25,
    commonInjuries: ['equipment-injury', 'repetitive-strain', 'amputation'] },
  { slug: 'warehouse',     name: 'Warehouse & Logistics', riskLevel: 'high',      riskMultiplier: 1.2,
    commonInjuries: ['back-injury', 'lifting-injury', 'repetitive-strain'] },
  { slug: 'transport',     name: 'Transportation',        riskLevel: 'high',      riskMultiplier: 1.2,
    commonInjuries: ['vehicle-accident', 'back-injury', 'neck-injury'] },
  { slug: 'healthcare',    name: 'Healthcare',            riskLevel: 'medium',    riskMultiplier: 1.1,
    commonInjuries: ['back-injury', 'needlestick', 'repetitive-strain'] },
  { slug: 'agriculture',   name: 'Agriculture',           riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['equipment-injury', 'fall-injury', 'heat-illness'] },
  { slug: 'retail',        name: 'Retail',                riskLevel: 'low',       riskMultiplier: 1.0,
    commonInjuries: ['slip-fall', 'lifting-injury', 'repetitive-strain'] },
  { slug: 'food-service',  name: 'Food Service',          riskLevel: 'medium',    riskMultiplier: 1.1,
    commonInjuries: ['burn-injury', 'slip-fall', 'repetitive-strain'] },
  { slug: 'mining',        name: 'Mining',                riskLevel: 'very-high', riskMultiplier: 1.5,
    commonInjuries: ['lung-disease', 'equipment-injury', 'head-injury'] },
  { slug: 'utilities',     name: 'Utilities',             riskLevel: 'high',      riskMultiplier: 1.3,
    commonInjuries: ['electrical-injury', 'fall-injury', 'burn-injury'] },
  { slug: 'office',        name: 'Office & Admin',        riskLevel: 'low',       riskMultiplier: 0.9,
    commonInjuries: ['carpal-tunnel', 'repetitive-strain', 'slip-fall'] },
  { slug: 'education',     name: 'Education',             riskLevel: 'low',       riskMultiplier: 0.9,
    commonInjuries: ['slip-fall', 'back-injury', 'ptsd'] },
]

export const INJURY_TYPES: InjuryType[] = [
  // Body part injuries
  { slug: 'back-injury',       name: 'Back & Spine Injury',         category: 'body-part',   bodyPart: 'back',
    scheduledWeeks: null, avgImpairmentRating: 15, avgMedicalCost: 45000, nyWeeks: null,  njWeeks: null },
  { slug: 'knee-injury',       name: 'Knee Injury',                  category: 'body-part',   bodyPart: 'leg',
    scheduledWeeks: 200,  avgImpairmentRating: 12, avgMedicalCost: 25000, nyWeeks: 288,   njWeeks: 315 },
  { slug: 'shoulder-injury',   name: 'Shoulder Injury',              category: 'body-part',   bodyPart: 'arm',
    scheduledWeeks: 160,  avgImpairmentRating: 14, avgMedicalCost: 30000, nyWeeks: 312,   njWeeks: 330 },
  { slug: 'hand-injury',       name: 'Hand & Wrist Injury',          category: 'body-part',   bodyPart: 'hand',
    scheduledWeeks: 244,  avgImpairmentRating: 10, avgMedicalCost: 20000, nyWeeks: 244,   njWeeks: 245 },
  { slug: 'foot-injury',       name: 'Foot & Ankle Injury',          category: 'body-part',   bodyPart: 'foot',
    scheduledWeeks: 205,  avgImpairmentRating: 10, avgMedicalCost: 18000, nyWeeks: 205,   njWeeks: 230 },
  { slug: 'neck-injury',       name: 'Neck & Cervical Injury',       category: 'body-part',   bodyPart: 'neck',
    scheduledWeeks: null, avgImpairmentRating: 12, avgMedicalCost: 38000, nyWeeks: null,  njWeeks: null },
  { slug: 'head-injury',       name: 'Head & Brain Injury (TBI)',    category: 'body-part',   bodyPart: 'head',
    scheduledWeeks: null, avgImpairmentRating: 25, avgMedicalCost: 85000, nyWeeks: null,  njWeeks: null },
  { slug: 'eye-injury',        name: 'Eye Injury / Vision Loss',     category: 'body-part',   bodyPart: 'eye',
    scheduledWeeks: 160,  avgImpairmentRating: 20, avgMedicalCost: 22000, nyWeeks: 160,   njWeeks: 200 },
  { slug: 'amputation',        name: 'Amputation',                   category: 'body-part',   bodyPart: 'varies',
    scheduledWeeks: 312,  avgImpairmentRating: 45, avgMedicalCost: 120000, nyWeeks: 312,  njWeeks: 330 },
  // Accident types
  { slug: 'fall-injury',       name: 'Fall / Slip & Trip',           category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 18, avgMedicalCost: 35000, nyWeeks: null,  njWeeks: null },
  { slug: 'equipment-injury',  name: 'Machinery & Equipment Injury', category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 50000, nyWeeks: null,  njWeeks: null },
  { slug: 'repetitive-strain', name: 'Repetitive Strain Injury (RSI)', category: 'accident',  bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 15000, nyWeeks: null,  njWeeks: null },
  { slug: 'lifting-injury',    name: 'Lifting & Overexertion',       category: 'accident',    bodyPart: 'back',
    scheduledWeeks: null, avgImpairmentRating: 13, avgMedicalCost: 28000, nyWeeks: null,  njWeeks: null },
  { slug: 'vehicle-accident',  name: 'Work Vehicle Accident',        category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 15, avgMedicalCost: 42000, nyWeeks: null,  njWeeks: null },
  { slug: 'burn-injury',       name: 'Burn Injury',                  category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 55000, nyWeeks: null,  njWeeks: null },
  { slug: 'electrical-injury', name: 'Electrical Injury',            category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 22, avgMedicalCost: 48000, nyWeeks: null,  njWeeks: null },
  { slug: 'heat-illness',      name: 'Heat Stroke / Heat Illness',   category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 20000, nyWeeks: null,  njWeeks: null },
  { slug: 'slip-fall',         name: 'Slip & Fall on Wet Surface',   category: 'accident',    bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 12, avgMedicalCost: 22000, nyWeeks: null,  njWeeks: null },
  // Occupational diseases
  { slug: 'carpal-tunnel',     name: 'Carpal Tunnel Syndrome',       category: 'occupational', bodyPart: 'hand',
    scheduledWeeks: 244,  avgImpairmentRating: 8,  avgMedicalCost: 12000, nyWeeks: 244,   njWeeks: 245 },
  { slug: 'hearing-loss',      name: 'Occupational Hearing Loss',    category: 'occupational', bodyPart: 'ear',
    scheduledWeeks: 150,  avgImpairmentRating: 15, avgMedicalCost: 8000,  nyWeeks: 150,   njWeeks: null },
  { slug: 'mesothelioma',      name: 'Mesothelioma / Asbestos Disease', category: 'occupational', bodyPart: 'lung',
    scheduledWeeks: null, avgImpairmentRating: 80, avgMedicalCost: 250000, nyWeeks: null, njWeeks: null },
  { slug: 'lung-disease',      name: 'Occupational Lung Disease',    category: 'occupational', bodyPart: 'lung',
    scheduledWeeks: null, avgImpairmentRating: 30, avgMedicalCost: 75000, nyWeeks: null,  njWeeks: null },
  { slug: 'ptsd',              name: 'Work-Related PTSD',            category: 'occupational', bodyPart: 'mental',
    scheduledWeeks: null, avgImpairmentRating: 20, avgMedicalCost: 30000, nyWeeks: null,  njWeeks: null },
  { slug: 'needlestick',       name: 'Needlestick / Blood Exposure', category: 'occupational', bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 5,  avgMedicalCost: 8000,  nyWeeks: null,  njWeeks: null },
  { slug: 'skin-disease',      name: 'Occupational Skin Disease',    category: 'occupational', bodyPart: 'skin',
    scheduledWeeks: null, avgImpairmentRating: 10, avgMedicalCost: 12000, nyWeeks: null,  njWeeks: null },
  { slug: 'chemical-exposure', name: 'Toxic Chemical Exposure',      category: 'occupational', bodyPart: 'varies',
    scheduledWeeks: null, avgImpairmentRating: 25, avgMedicalCost: 60000, nyWeeks: null,  njWeeks: null },
]
