export const INJURY_COST_DATA = [
  {
    cause:      'Motor Vehicle',
    avgCost:    91433,
    vsAverage:  '+93%',
    trend:      'up' as const,
    note:       'Highest cost category',
    source:     'NCCI via NSC 2024',
  },
  {
    cause:      'Burns',
    avgCost:    64973,
    vsAverage:  '+37%',
    trend:      'up' as const,
    note:       'High medical costs',
    source:     'NCCI via NSC 2024',
  },
  {
    cause:      'Falls or Slips',
    avgCost:    54499,
    vsAverage:  '+15%',
    trend:      'stable' as const,
    note:       'Most common lost-time injury',
    source:     'NCCI via NSC 2024',
  },
  {
    cause:      'Caught In/Between',
    avgCost:    47749,
    vsAverage:  '+1%',
    trend:      'stable' as const,
    note:       'Near overall average',
    source:     'NCCI via NSC 2024',
  },
  {
    cause:      'All Claims Average',
    avgCost:    47316,
    vsAverage:  '—',
    trend:      'baseline' as const,
    note:       '2022–2023 baseline',
    source:     'NCCI via NSC 2024',
    baseline:   true,
  },
  {
    cause:      'Overexertion',
    avgCost:    38000,
    vsAverage:  '-20%',
    trend:      'down' as const,
    note:       'Most frequent claim type',
    source:     'NCCI 2024 (estimated range)',
    estimated:  true,
  },
  {
    cause:      'Struck By Object',
    avgCost:    35000,
    vsAverage:  '-26%',
    trend:      'stable' as const,
    note:       'Common in construction',
    source:     'NCCI 2024 (estimated range)',
    estimated:  true,
  },
]

export const STATE_BENEFIT_RATES_2025 = [
  {
    state:      'California',
    slug:       'california',
    ttdRate:    '66.67%',
    maxWeekly:  1619,
    minWeekly:  242,
    sol:        '1 year',
    statute:    'Cal. Labor Code §4650',
    statLink:   'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=4650.&lawCode=LAB',
  },
  {
    state:      'Texas',
    slug:       'texas',
    ttdRate:    '70%',
    maxWeekly:  1066,
    minWeekly:  150,
    sol:        '1 year',
    statute:    'Tex. Labor Code §408.102',
    statLink:   'https://statutes.capitol.texas.gov/Docs/LA/htm/LA.408.htm',
    note:       'Non-subscriber employers complicate claims',
  },
  {
    state:      'Florida',
    slug:       'florida',
    ttdRate:    '66.67%',
    maxWeekly:  1284,
    minWeekly:  20,
    sol:        '2 years',
    statute:    'Fla. Stat. §440.15',
    statLink:   'https://www.flsenate.gov/Laws/Statutes/2024/440.15',
  },
  {
    state:      'New York',
    slug:       'new-york',
    ttdRate:    '66.67%',
    maxWeekly:  1145,
    minWeekly:  150,
    sol:        '2 years',
    statute:    'NY WCL §15',
    statLink:   'https://www.nysenate.gov/legislation/laws/WKC/15',
  },
  {
    state:      'Illinois',
    slug:       'illinois',
    ttdRate:    '66.67%',
    maxWeekly:  1897,
    minWeekly:  0,
    sol:        '3 years',
    statute:    '820 ILCS 305/8(b)',
    statLink:   'https://www.ilga.gov/legislation/ilcs/ilcs4.asp?DocName=082000050HArt.+VIII',
  },
  {
    state:      'Pennsylvania',
    slug:       'pennsylvania',
    ttdRate:    '66.67%',
    maxWeekly:  1273,
    minWeekly:  636,
    sol:        '3 years',
    statute:    '77 P.S. §511',
    statLink:   'https://www.legis.state.pa.us/cfdocs/legis/LI/consCheck.cfm?txtType=HTM&ttl=77&div=0&chpt=5',
  },
  {
    state:      'Ohio',
    slug:       'ohio',
    ttdRate:    '72%',
    maxWeekly:  1224,
    minWeekly:  0,
    sol:        '2 years',
    statute:    'Ohio Rev. Code §4123.56',
    statLink:   'https://codes.ohio.gov/ohio-revised-code/section-4123.56',
    note:       'State fund only',
  },
  {
    state:      'Georgia',
    slug:       'georgia',
    ttdRate:    '66.67%',
    maxWeekly:  800,
    minWeekly:  50,
    sol:        '1 year',
    statute:    'O.C.G.A. §34-9-261',
    statLink:   'https://law.justia.com/codes/georgia/title-34/chapter-9/article-4/section-34-9-261/',
  },
  {
    state:      'North Carolina',
    slug:       'north-carolina',
    ttdRate:    '66.67%',
    maxWeekly:  1266,
    minWeekly:  30,
    sol:        '2 years',
    statute:    'N.C. Gen. Stat. §97-29',
    statLink:   'https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_97/GS_97-29.html',
  },
  {
    state:      'Michigan',
    slug:       'michigan',
    ttdRate:    '80%',
    maxWeekly:  1118,
    minWeekly:  0,
    sol:        '2 years',
    statute:    'Mich. Comp. Laws §418.351',
    statLink:   'https://www.legislature.mi.gov/Laws/MCL?objectName=MCL-418-351',
    note:       'Higher rate than most states',
  },
]
